<?xml version="1.0"?>
<package format="3">
  <name>yolov8_ros</name>
  <version>1.0.0</version>
  <description>The yolov8_ros package</description>
  
  <maintainer email="choi.6f@gmail.com">Team SOBITS</maintainer>
  <license>TODO</license>

  <!-- Build and exec dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>ament_index_cpp</build_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>ament_index_cpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
